### ISSUE TITLE
How to use BinTuner

### ISSUE THREAD

**Issue by randomFriendlyGuy** [BinTuner/Dev#1]
Hello, thanks for your execellent research and friendly released code. However, it seems you do not mention how to use this this tool to get the nearly optimal compiler flags to create binaries.
May I ask whether you will detial the steps to use BinTuner? Thanks in advance.

**Comment by stonedreamforest** [comment]
in short, it's just an experimental product.

**Comment by BinTuner** [comment]
@randomFriendlyGuy @stonedreamforest 
Thanks for your interest in BinTuner, we will release more details after the PLDI events and do our best to provide technical support to help everyone ：）

**Comment by BinTuner** [comment]
Hi guys  : ）

Thank you very much for your interest and feedback!

This question has been answered, let me close it for now and if you have other questions, feel free to open a new one.

All the best,
