### ISSUE TITLE
Set up how many times to run

### ISSUE THREAD

**Issue by Patrick-ICT** [BinTuner/Dev#10]
Hi,
I am compiling the SPEC using main_clang.py. Basically, I can generate the tuned binary, which is exciting :)
After that, I am wondering how to set the termination condition.
From the README and the main_clang.py, there are two paths monitoring the change of MAX value. After the MAX value remains unchanged 10 times, the increase is less than 0.05 for 10 times, or the sum of trigger time of these two conditions has reached 10, it would terminate.
So what's the argument (for the command "python main.py 10" is 10) used for? I have changed it to 100 but the termination is still triggered by the above two paths.
Should I change the termination threshold to higher, like 100, or 10 is enough?
Thanks for your time and have a nice day!

**Comment by BinTuner** [comment]
Hi there,

Thank you very much for your interest in our paper and for being prepared to try out BinTuner!

10 or 100 is the pre-set maximum number of iterations to compile, and yes, iterative compilation will stop when those two conditions are met. You can consider modifying those two conditions and try again, or comment out the source code for those two conditions and try again. I hope this information is helpful to you.

If you have a good idea, encouraged you to modify/optimize this stop condition :)

Thanks again for your feedback and for your interest in BinTuner.

Have a great day!
