### ISSUE TITLE
Strategies for running BinTuner much faster without much compromises

### ISSUE THREAD

**Issue by dumblob** [BinTuner/Dev#2]
Currently BinTuner focuses on quality. To make it a practical tool, it'd need to provide subsecond answers for small programs (say 1000 SLOC of *C*).

Please share your ideas here how could that be achieved without much compromising the quality of the outcomes.

1. Based on some fast heuristics (e.g. based on experience with "BinTuning" of previous apps) or source code available or some annotations in debug build or whatever, choose only a very small percentage (maybe less than 0.5%) of all instructions at interesting places and run BinTuner only on those.
2. Restrict or extend the operations the genetic algorithm can do leading to faster convergence.
3. Pre-prepare the binary in some way so that the initial phases the genetic algorithm currently does can be "skipped". In other words, shuffle with the instructions before the genetic algorithm starts in a way resembling the first few hundreds/thousands iterations/populations of the genetic algorithm but **in one step**. Yet in other words, prepare quickly more optimal default initial state of the input instead of relying on the genetic algorithm all the way down from the very beginning.
4. Techniques used by [superoptimizers](https://en.wikipedia.org/wiki/Superoptimization ).

**Comment by BinTuner** [comment]
@dumblob  Thank you so much for your interest in BinTuner and for sharing these good ideas :)
yes, these may have the opportunity to improve the speed of convergence.
we're exploring better ways to converge faster and make iteration compilation more efficient.

**Comment by dumblob** [comment]
I've added superoptimizers (https://en.wikipedia.org/wiki/Superoptimization ) to the list above.

Btw. it might make sense to add BinTuner to the list on the wikipedia page :wink:.

**Comment by BinTuner** [comment]
@dumblob 👍 Cool, thanks!

**Comment by BinTuner** [comment]
Hi guys  : ）

Thank you very much for your interest and feedback!

This question has been answered, let me close it for now and if you have other questions, feel free to open a new one.

All the best,
