### ISSUE TITLE
z3 crashes in running the example in the README

### ISSUE THREAD

**Issue by chenju2k6** [BinTuner/Dev#5]
Program Start
['GGA']
beformutation
************************ Z3 ************************

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
api::object::inc_ref (this=this@entry=0xffffffff918ba0a8) at /z3/src/api/api_context.cpp:38
38          void object::inc_ref() { m_ref_count++; }
(gdb) bt
#0  api::object::inc_ref (this=this@entry=0xffffffff918ba0a8) at /z3/src/api/api_context.cpp:38
#1  0x00007f451a0f0c88 in Z3_solver_inc_ref (c=0x55a49197c7a8, s=0xffffffff918ba0a8) at /z3/src/api/api_solver.cpp:379
#2  0x00007f45bd37cdae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007f45bd37c71f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#4  0x00007f45bd58fbf4 in _ctypes_callproc () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#5  0x00007f45bd58f5f5 in ?? () from /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so
#6  0x000055a4902da6c0 in PyEval_EvalFrameEx ()
#7  0x000055a4902da4c6 in PyEval_EvalFrameEx ()
#8  0x000055a4902d2d5a in PyEval_EvalCodeEx ()
#9  0x000055a4902eebc9 in ?? ()
#10 0x000055a490306efe in ?? ()
#11 0x000055a4902be8be in PyObject_Call ()
#12 0x000055a4902f23cc in PyInstance_New ()
#13 0x000055a4902da6c0 in PyEval_EvalFrameEx ()
#14 0x000055a4902d2d5a in PyEval_EvalCodeEx ()
#15 0x000055a4902dae3c in PyEval_EvalFrameEx ()
#16 0x000055a4902da4c6 in PyEval_EvalFrameEx ()
#17 0x000055a4902da4c6 in PyEval_EvalFrameEx ()
#18 0x000055a4902d2d5a in PyEval_EvalCodeEx ()
#19 0x000055a4902dae3c in PyEval_EvalFrameEx ()
#20 0x000055a4902d2d5a in PyEval_EvalCodeEx ()
#21 0x000055a4902dae3c in PyEval_EvalFrameEx ()
#22 0x000055a4902da4c6 in PyEval_EvalFrameEx ()
#23 0x000055a4902da4c6 in PyEval_EvalFrameEx ()
#24 0x000055a4902d2d5a in PyEval_EvalCodeEx ()
#25 0x000055a4902dae3c in PyEval_EvalFrameEx ()
#26 0x000055a4902d2d5a in PyEval_EvalCodeEx ()
#27 0x000055a4902d2899 in PyEval_EvalCode ()
#28 0x000055a4903030ef in ?? ()
#29 0x000055a4902fe2f2 in PyRun_FileExFlags ()
#30 0x000055a4902fdded in PyRun_SimpleFileExFlags ()
#31 0x000055a4902acc99 in Py_Main ()
#32 0x00007f45bf87fbf7 in __libc_start_main (main=0x55a4902ac710 <main>, argc=3, argv=0x7ffec001b838, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffec001b828) at ../csu/libc-start.c:310
#33 0x000055a4902ac62a in _start ()

**Comment by BinTuner** [comment]
@chenju2k6 

Thank you for your interest in BinTuner.

According to your error message, the error is probably due to Z3, you can try to fix Z3 issue first to make sure it works since we use Z3 in BinTuner.

**Comment by BinTuner** [comment]
Hi @chenju2k6 

I am using z3-solver 4.8.14.0 (pip install z3-solver), I just try to install it again and this version works well.
Can you let me know which version of z3-solver you are reporting so that I can go find out what the problem is?

**Comment by BinTuner** [comment]
Hi @chenju2k6 

I've tried a few different solutions to your Z3 issue over the past few days. I have updated some source files and tried to install BinTuner a few times, it should work well now.
Feel free to re-download all the source programs and run BinTuner again.
Let me know if you encounter a new issue.

**Comment by chenju2k6** [comment]
Thanks a lot for the reply. Closing the issue.
