### ISSUE TITLE
About Constraints between GCC Options

### ISSUE THREAD

**Issue by orangehn** [BinTuner/Dev#8]
Hello, I am very interested in your work.
At present, I have encountered a problem. When I compiler benchmarks with GCC, I turn on the specified single or several optimization options based on -O0. Unfortunately, I found that the optimization options did not work.
I noticed that in your paper it is mentioned that "In some cases, two options negatively influence each other, and turning on them together leads to a compilation error. Some other compilation options only work when a certain option has been activated. For example, -fpartial-inlining has any effect only when -finline-functions is turned on. To avoid compilation errors caused by such constraints, we manually translate them into logical first-order formulas offline after understanding the compiler manual.". 

I can't find the constraint file in the code https://github.com/BinTuner/Dev , could you please share it with me?
Also, do you have any good suggestions to solve this problem?
Thank you!

**Comment by BinTuner** [comment]
Hi there,

Thank you very much for your interest in our paper and for being prepared to try out BinTuner!

I think you may have missed the important part, which is detailed in the paper and the GitHub description file. Don't worry, let me show you where it is : )

We use Z3 Prover to analyze all generated optimization option sequences for conflicts and make changes to conflicting options for greater compiling success. For more details, please refer [Z3Prover](https://github.com/BinTuner/Dev/blob/main/BinTuner/opentuner/search/Z3Prover.py).

All the Best,
